debug: http transport

clean: http-clean transport-clean

# Modules
http:
	echo "Http"
	cd http;make
	echo "End Http\n"

http-clean:
	cd http;make clean

transport:
	echo "Transport"
	cd transport;make
	echo "End Transport\n"

transport-clean:
	cd transport;make clean
